tables/safety/dmt01.qmd
=> Fix joins in DMT01

DESCRIPTION, LICENSE, index.qmd
=> add license and pkg authors

tables/adverse-events/aet03.qmd, tables/lab-results/lbt05.qmd, tables/lab-results/lbt08.qmd, tables/lab-results/lbt13.qmd, tables/lab-results/lbt14.qmd, tables/lab-results/lbt15.qmd, tlg-index.qmd
=> Small general fixes

listings/other/lbl01.qmd, listings/other/lbl01_rls.qmd, tables/lab-results/lbt05.qmd, tables/lab-results/lbt08.qmd, tables/lab-results/lbt13.qmd, tables/lab-results/lbt14.qmd, tables/safety/vst02.qmd
Part of #25 
Updated templates (also updated in `scda.test`):
LBL01
LBL01_RLS
LBT05
LBT07
LBT08
LBT14
VST02
=> Template updates for new data version

listings/other/ael01.qmd, listings/other/ael01_nollt.qmd, listings/other/ael02.qmd, listings/other/ael02_ed.qmd, listings/other/ael03.qmd, listings/other/ael04.qmd, listings/other/cml01.qmd, listings/other/cml02a_gl.qmd, listings/other/cml02b_gl.qmd, listings/other/dsl01.qmd, listings/other/dsl02.qmd, listings/other/dsur4.qmd, listings/other/egl01.qmd, listings/other/exl01.qmd, listings/other/lbl01.qmd, listings/other/lbl01_rls.qmd, listings/other/lbl02a.qmd, listings/other/lbl02a_rls.qmd, listings/other/lbl02b.qmd, listings/other/mhl01.qmd, listings/other/oncl01.qmd, listings/other/vsl01.qmd, listings/pharmacokinetic/adal02.qmd, listings/pharmacokinetic/pkcl01.qmd, listings/pharmacokinetic/pkcl02.qmd, listings/pharmacokinetic/pkpl01.qmd, listings/pharmacokinetic/pkpl02.qmd, listings/pharmacokinetic/pkpl04.qmd, tlg-index.qmd
=> Add missing "Session Info" tab to listings

tables/adverse-events/aet02.qmd, tables/adverse-events/aet09.qmd, tables/safety/cmt01.qmd, tables/safety/mht01.qmd
=> fix sorting for more ARMs

tables/efficacy/coxt01.qmd, tables/efficacy/coxt02.qmd
=> Update COXT01 and COXT02

tables/adverse-events/aet02.qmd, tables/adverse-events/aet04.qmd, tables/adverse-events/aet07.qmd, tables/safety/cmt02_pt.qmd
=> Update after `tern` indentation fixes

tables/other/rmpt04.qmd
=> Fix rmpt04

.github/workflows/check.yml, .github/workflows/docs.yml, book/graphs/pharmacokinetic/pkcg01.qmd, book/graphs/pharmacokinetic/pkcg02.qmd, book/graphs/pharmacokinetic/pkcg03.qmd, book/listings/pharmacokinetic/adal02.qmd, book/listings/pharmacokinetic/pkcl01.qmd, book/tables/pharmacokinetic/adat01.qmd, book/tables/pharmacokinetic/adat02.qmd, book/tables/pharmacokinetic/adat03.qmd, book/tables/pharmacokinetic/adat04a.qmd, book/tables/pharmacokinetic/adat04b.qmd, book/tables/pharmacokinetic/pkct01.qmd
follow up on https://github.com/insightsengineering/tlg-catalog/pull/62
=> fix paths in docs workflow

book/.gitignore, book/tables/adverse-events/aet04.qmd
the docs build on main failed - this PR aims to fix it
=> renv.ignore save chunk

book/tables/adverse-events/aet02_smq.qmd, book/tables/adverse-events/aet05_all.qmd, book/tables/adverse-events/aet06_smq.qmd, book/tables/adverse-events/aet09_smq.qmd, book/tables/efficacy/dort01.qmd, book/tables/efficacy/mmrmt01.qmd, book/tables/efficacy/ttet01.qmd, book/tables/safety/enrollment01.qmd
Part of https://github.com/insightsengineering/tern/issues/992
=> Sanitize tables

book/tables/pharmacokinetic/pkpt11.qmd, package/tests/testthat/_snaps/pkpt11/markdown-snaps.md
Also aligned top left info with content.
Closes #103
=> Refactor PKPT11 to pass sanitation checks

book/tables/adverse-events/aet02.qmd, book/tables/adverse-events/aet09.qmd
=> Simplify `count_occurrences` indent mods

book/tables/vital-signs/vst01.qmd, book/tables/vital-signs/vst02.qmd
=> `tdata` to `teal_data`: tables -> vital-signs

book/tables/concomitant-medications/cmt01.qmd, book/tables/concomitant-medications/cmt01a.qmd, book/tables/concomitant-medications/cmt01b.qmd, book/tables/concomitant-medications/cmt02_pt.qmd
=> `tdata` to `teal_data`: tables -> concomitant-medication

book/tables/medical-history/mht01.qmd
=> `tdata` to `teal_data`: tables -> medical-history

book/tables/exposure/ext01.qmd
=> `tdata` to `teal_data`: tables -> exposure

book/tables/disposition/dst01.qmd, book/tables/disposition/pdt01.qmd
=> `tdata` to `teal_data`: tables -> disposition

book/tables/lab-results/lbt01.qmd, book/tables/lab-results/lbt02.qmd, book/tables/lab-results/lbt03.qmd, book/tables/lab-results/lbt04.qmd, book/tables/lab-results/lbt07.qmd, book/tables/lab-results/lbt11.qmd, book/tables/lab-results/lbt11_bl.qmd, book/tables/lab-results/lbt13.qmd, book/tables/lab-results/lbt14.qmd, book/tables/lab-results/lbt15.qmd
=> `tdata` to `teal_data`: tables -> lab-results

book/tables/ECG/egt01.qmd, book/tables/ECG/egt03.qmd, book/tables/ECG/egt05_qtcat.qmd
=> `tdata` to `teal_data`: tables -> ECG

book/tables/efficacy/aovt01.qmd, book/tables/efficacy/aovt02.qmd, book/tables/efficacy/cfbt01.qmd, book/tables/efficacy/cmht01.qmd, book/tables/efficacy/coxt01.qmd, book/tables/efficacy/coxt02.qmd, book/tables/efficacy/dort01.qmd, book/tables/efficacy/lgrt02.qmd, book/tables/efficacy/mmrmt01.qmd, book/tables/efficacy/onct05.qmd, book/tables/efficacy/rspt01.qmd, book/tables/efficacy/ttet01.qmd
=> `tdata` to `teal_data`: tables -> efficacy

book/tables/ECG/egt02.qmd
part of part of https://github.com/insightsengineering/coredev-tasks/issues/488
example remained from tables -> ECG
=> tdata to teal_data: egt02

book/tables/efficacy/mmrmt01.qmd
=> Fix baseline counts in MMRMT01

book/tables/efficacy/ratet01.qmd
Close #21 per title description
=> add a negative binomial example to ratet01

book/graphs/other/kmg01.qmd, book/index.qmd, book/tables/efficacy/ttet01.qmd, book/tables/lab-results/lbt11.qmd, book/tables/lab-results/lbt11_bl.qmd, package/DESCRIPTION
=> Update use of deprecated `strat` argument from `tern`

package/tests/testthat/_snaps/stable/tables-efficacy-mmrmt01.md, package/tests/testthat/_snaps/stable/tables-efficacy-rbmit01.md, package/tests/testthat/_snaps/stable/tables-efficacy-ttet01.md, package/tests/testthat/_snaps/stable/tables-lab-results-lbt11_bl.md
=> Fix failing integration tests

book/_quarto.yml
there are some problems with the font
let's come back to the default `svg` engine
this is the current state which is obviously wrong
=> replace svglite with svg
